version: '3'
services:
  backend:
    build:
      context: ./java-back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend  # Corrected service name
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
